# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://commoncause.is'
baseurl: ''
title: 'Common Cause'
description: 'a collaboration project'
permalink: pretty
logo: 'https://en.gravatar.com/userimage/37173417/a4270ccd26d8446e908f139b4eb2024a.png'

# Pagination
paginate: 5
paginate_path: art/page:num

# Header nav
navigation_header:
  Home: /
  Art: /art/

# Footer nav
navigation_footer:
  Back to top: '#top'

# Collections
collections:
  posts:
    title: Art
    output: true
    description: ''
    feature_text: ''
    feature_image: '/uploads/20170127_235120.jpg'
